//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContinuousData
    {
        public int Id { get; set; }
        public int WellId { get; set; }
        public System.DateTime Time { get; set; }
        public double DiffPressure { get; set; }
        public double Pressure { get; set; }
        public double Temperature { get; set; }
    
        public virtual Well Well { get; set; }
    }
}
